name: Build Solana v1.18.20

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Solana v1.18.20
      run: |
        git clone --depth 1 --branch v1.18.20 https://github.com/solana-labs/solana.git
        cd solana
        echo "BUILD_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl git build-essential pkg-config libssl-dev libudev-dev clang cmake

    - name: Build Solana
      run: |
        cd $BUILD_DIR/solana
        cargo build --release

    - name: Upload Solana binary
      uses: actions/upload-artifact@v4
      with:
        name: solana-bin
        path: |
          ${{ env.BUILD_DIR }}/solana/target/release/solana
